<p><strong>POSITIVE</strong>HEALTH is registered with The Data Protection Commissioner.</p>

<p>Outlined below is the <strong>POSITIVE</strong>HEALTH policy with regard to the privacy of the users of our website and any sub-sites. By visiting these sites, you are agreeing to the terms of this privacy statement. If you are not happy with the contents of this statement and do not wish your information to be recorded, you may leave this site.</p>


<p class="im-lblue">General Statement</p>

<p><strong>POSITIVE</strong>HEALTH fully respects your rights to privacy and will not collect any personal information without your clear permission. Any personal information which you volunteer when you visit our website through email alerts or when using our online forms will be treated with the highest standard of security and confidentiality. This is strictly in accordance with applicable Data Protection legislation.</p>


<p><strong>Collection and Use of Personal Information</strong></p>

<p>We take every precaution to protect the confidentiality of your personal information that you supply. For general web browsing, certain information is recorded in the website log files which may include:</p>


<ul class="disc">
<li>The top-level domain name from which you access the internet;</li>
<li>The IP address of the computer from which you access the website;</li>
<li>The date and time each computer accesses the website;</li>
<li>The pages accessed and the documents downloaded by each computer;</li>
<li>The type and version of the browsers being used to access the website;</li>
<li>The addresses of any third-party web-pages which refer visitors to our website;</li>
<li>Keywords used in search engines and directories to find our website; and/or</li>
<li>Keywords and phrases used to search our website.</li>
</ul>

<p>This information is used for statistical purposes only including:</p>

<ul class="disc">
<li>To find out how many people are visiting our sites;</li>
<li>To identify what pages are accessed more frequently;</li>
<li>To help us improve the information we are supplying to our users; and</li>
<li>To make our site more user friendly.</li>
</ul>

<p><strong>Use of Cookies</strong></p>

<p>Cookies are small pieces of information, stored in simple text files, placed on your computer by a website. Some cookies can be read by the website on your subsequent visits. The information stored in a cookie may relate to your browsing habits on the webpage, or a unique identification number so that the website can remember you on your return visit. Other cookies are deleted when you close your browser and only relate to the working of the website. Generally speaking, cookies do not contain personal information from which you can be identified, unless you have furnished such information to the website.</p>

<p>Cookies are in use in several places on this website:</p>

<ul class="disc">
<li>When you first visit this website, you will see a message informing you about cookies. If you click the <strong>‘ACCEPT’</strong> button, a cookie will be set which records your preference.</li>
<li>Cookies from Google are set because this website uses Google Analytics to analyse website usage.</li>
<li>This website uses Google Custom Search to provide the site’s search functionality. Google may set cookies when you use the search function. You can find Google’s privacy policy here: https://www.google.com/policies/privacy/. </li>
<li>Cookies from Google may also be set when Google Maps are displayed on this website.</li>
<li>Cookies from Google may also be set when YouTube or Vimeo videos are displayed on this website.</li>
</ul>

<p>Most browsers allow you to turn off cookies or to customise your settings for cookies. To find out how to do this, see the ‘Help’ menu on your browser. Please note that if you turn off cookies or change your settings, some features may not work correctly.</p>


<p><strong>Usage of Google Analytics</strong></p>

<p>This website uses Google Analytics, a web analytics service provided by Google, Inc. ("<strong>Google</strong>"). Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyse how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>


<p><strong>Links</strong></p>

<p>The <strong>POSITIVE</strong>HEALTH website contains links to other sites. We are not responsible for the privacy standards of other websites. We encourage you to be aware of this when you leave our site. This privacy statement relates only to the privacy practices in connection with our website and any sub-sites.</p>


<p class="im-lblue">Notification of changes to these Website Terms & Conditions</p>

<p><strong>POSITIVE</strong>HEALTH reserves the right to amend this statement at any future date and will post any substantive changes here.</p>
 

<p class="im-lblue">Contact</p>

<p>Should you have any queries regarding these Website Terms & Conditions then please email <a href="mailto:legal@phgp.ie">legal@phgp.ie</a> </p>